const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {webcrypto}=require('node:crypto');
const {indexedDB}=require('fake-indexeddb');
const adhan=require('adhan');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,'web',name),'utf8');
function engines(){const w={Date,Intl,JSON,TextEncoder,TextDecoder,crypto:webcrypto,indexedDB,URL,console,btoa,atob};w.window=w;vm.createContext(w);for(const name of ['nur-deen-core.js','nur-deen-content.js','nur-deen-harden.js','nur-ai-secrets.js','nur-deen-store.js','nur-vault.js','nur-deen-backup.js'])vm.runInContext(read(name),w,{filename:name});return w;}
const toJSON=x=>JSON.parse(JSON.stringify(x));
const storage=()=>{const map=new Map();return {getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k),snapshot:()=>Object.fromEntries(map)};};
function fixture(id,count,edition='quran-uthmani'){return {number:id,numberOfAyahs:count,name:'Fixture',englishName:'Fixture',edition:{identifier:edition,englishName:'Fixture edition'},ayahs:Array.from({length:count},(_,i)=>({numberInSurah:i+1,text:'Test fixture verse '+(i+1)}))};}

test('canonical Quran references and corpus metadata are validated',()=>{const w=engines(),D=w.NurDeenCore,C=w.NurDeenContent;assert.equal(C.COUNTS.length,114);assert.equal(C.COUNTS.reduce((a,b)=>a+b,0),6236);assert.equal(D.verseKey('1:7'),true);assert.equal(D.verseKey('1:8'),false);assert.equal(D.verseKey('114:6'),true);assert.equal(D.verseKey('114:7'),false);assert.throws(()=>D.validateChapter({code:200,data:fixture(1,6)},1,'quran-uthmani'));assert.equal(D.validateChapter({code:200,data:fixture(1,7)},1,'quran-uthmani').count,7);const full={code:200,data:{edition:{identifier:'quran-uthmani',englishName:'Fixture'},surahs:C.COUNTS.map((n,i)=>fixture(i+1,n))}};assert.equal(D.validateCorpus(full,'quran-uthmani').length,114);full.data.surahs[0].ayahs.pop();assert.throws(()=>D.validateCorpus(full,'quran-uthmani'));});

test('reading and Dhikr never mutate primary tracking data or invent prior records',()=>{const w=engines(),D=w.NurDeenCore;const tracking={days:{'2026-09-08':{prayers:[true,false,false,false,false]}},meta:{startedOn:'2026-09-08'}};const before=JSON.stringify(tracking);let s=D.reading(D.empty(),'2:255','bookmark');s=D.reading(s,'2:255','read');assert.deepEqual(toJSON(s.reading.bookmarks),['2:255']);assert.deepEqual(toJSON(s.reading.read),['2:255']);assert.equal(s.reading.last,'2:255');assert.equal(JSON.stringify(tracking),before);assert.deepEqual(toJSON(s.prayer.offsets),{fajr:0,dhuhr:0,asr:0,maghrib:0,isha:0});});

test('manual prayer times respect selected timezone, DST and exact local dates',()=>{const D=engines().NurDeenCore;assert.equal(D.zonedInstant('2026-09-09','05:30','Asia/Kolkata'),'2026-09-09T00:00:00.000Z');assert.throws(()=>D.zonedInstant('2026-03-08','02:30','America/New_York'),/does not exist/);assert.equal(D.zonedInstant('2026-11-01','01:30','America/New_York',Date.parse('2026-11-01T05:30:00Z')),'2026-11-01T05:30:00.000Z');assert.equal(D.zonedInstant('2026-11-01','01:30','America/New_York',Date.parse('2026-11-01T06:30:00Z')),'2026-11-01T06:30:00.000Z');});

test('local Adhan calculations, offsets and manual overrides produce real instants',()=>{const D=engines().NurDeenCore;const p=D.empty().prayer;p.location={latitude:11.15,longitude:76.05,timeZone:'Asia/Kolkata',label:'Test location'};const normal=D.prayerTimes(adhan,p,'2026-09-09');assert.equal(normal.estimated,true);assert.equal(Object.keys(normal.instants).length,5);assert.equal(D.localDate(normal.instants.fajr,'Asia/Kolkata'),'2026-09-09');p.offsets.fajr=5;const shifted=D.prayerTimes(adhan,p,'2026-09-09');assert.equal(Date.parse(shifted.instants.fajr)-Date.parse(normal.instants.fajr),300000);p.manual['2026-09-09']={fajr:'05:30'};const corrected=D.prayerTimes(adhan,p,'2026-09-09');assert.equal(D.resolvedPrayer(corrected,'fajr'),'2026-09-09T00:00:00.000Z');const plan=D.reminderPlan([corrected],Date.parse('2026-09-08T00:00:00Z'));assert.equal(plan.length,5);assert.equal(plan.find(x=>x.extra.name==='fajr').schedule.at.toISOString(),'2026-09-09T00:00:00.000Z');assert.equal(new Set(plan.map(x=>x.id)).size,5);});

test('Gemini transport uses header-only credentials, paginates models and redacts errors',async()=>{const D=engines().NurDeenCore,key='dummy-test-key-do-not-use',calls=[];const fake=async(url,options)=>{calls.push({url,options});return {ok:true,text:async()=>JSON.stringify(url.includes(':generateContent')?{candidates:[{content:{parts:[{text:'OK'}]}}]}:{models:[{name:'models/gemini-test',displayName:'Test model',supportedGenerationMethods:['generateContent']}],nextPageToken:calls.length===1?'next-page':''})};};const models=await D.models(fake,key);assert.equal(models.length,1);assert.equal(models[0].name,'models/gemini-test');const body=D.requestBody([],'Explain a concept');assert.equal(JSON.stringify(body).includes('private tracking'),false);assert.equal(body.contents.length,1);const answer=await D.generate(fake,key,models[0].name,body);assert.equal(answer,'OK');for(const c of calls){assert.equal(c.options.headers['x-goog-api-key'],key);assert.equal(c.url.includes(key),false);}assert.throws(()=>D.modelName('evil/../path'));assert.equal(D.safeError(403).includes(key),false);await assert.rejects(D.generate(async()=>({ok:false,status:403}),key,models[0].name,body),/rejected/);});

test('Gemini context is opt-in and bounded, with no automatic personal record access',()=>{const D=engines().NurDeenCore;const plain=D.requestBody([],'Question');const selected=D.requestBody([],'Question','Quran 2:255 — explicitly selected');assert.equal(JSON.stringify(plain).includes('2:255'),false);assert.ok(JSON.stringify(selected).includes('2:255'));assert.throws(()=>D.requestBody([],'   '));assert.ok(JSON.stringify(D.requestBody([],'x','a'.repeat(10000))).length<10000);});

test('encrypted API key storage supports session, lock, wrong passphrase and deletion',async()=>{const w=engines(),vault=w.NurAISecrets.createStore({crypto:webcrypto,indexedDB}),key='dummy-api-key-123';await vault.clear();vault.setSession(key);assert.equal(await vault.use(x=>x),key);vault.lock();assert.equal(vault.hasKey(),false);await vault.save(key,'a long private passphrase');const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(w.NurAISecrets.DB);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const record=await new Promise((resolve,reject)=>{const r=db.transaction('secrets').objectStore('secrets').get('gemini');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();assert.equal(JSON.stringify(record).includes(key),false);assert.equal(record.version,1);vault.lock();await assert.rejects(vault.unlock('incorrect passphrase'));assert.equal(vault.hasKey(),false);await vault.unlock('a long private passphrase');assert.equal(await vault.use(x=>x),key);await vault.clear();assert.equal(await vault.hasSaved(),false);assert.equal(vault.hasKey(),false);});

test('offline content cache validates chapters and preserves previous data on storage failures',async()=>{const w=engines(),memory=storage();const s=w.NurDeenStore.create({core:w.NurDeenCore,content:w.NurDeenContent,storage:memory,indexedDB,adhan,now:()=>Date.parse('2026-09-09T08:00:00Z'),fetch:async(url)=>url.includes('quran-uthmani.json')?{ok:false,status:404}:{ok:true,text:async()=>JSON.stringify({code:200,data:fixture(1,7)})}});const chapter=await s.chapter(1);assert.equal(chapter.count,7);const result=await s.search('fixture verse 2');assert.ok(result.some(x=>x.key==='1:2'));s.commit(x=>{x.reading.last='1:2';});const before=JSON.stringify(s.getState());const original=memory.setItem;memory.setItem=()=>{throw Error('quota');};assert.throws(()=>s.commit(x=>{x.reading.last='1:3';}));assert.equal(JSON.stringify(s.getState()),before);memory.setItem=original;assert.equal(s.countDhikr('tasbih',1,'2026-09-09'),1);assert.equal(s.getDhikr()['2026-09-09'].tasbih,1);});

test('unsupported native reminder delivery fails without claiming success',async()=>{const w=engines(),s=w.NurDeenStore.create({core:w.NurDeenCore,content:w.NurDeenContent,storage:storage(),indexedDB,adhan,capacitor:{isNativePlatform:()=>false}});assert.equal(s.notificationAvailable(),false);await assert.rejects(s.setReminders(true),/unavailable/);assert.equal(s.getState().prayer.reminders,false);});

test('Deen backup includes reading and counters but excludes API credentials',()=>{const w=engines(),V=w.NurVault,D=w.NurDeenCore,S=w.NurDeenStore,memory=storage();const tracking={meta:{startedOn:'2026-09-09',apiKey:'dummy-secret-should-not-export'},days:{}};let deen=D.reading(D.empty(),'2:255','bookmark');memory.setItem(D.KEY,JSON.stringify(deen));memory.setItem(S.DHIKR_KEY,JSON.stringify({'2026-09-09':{tasbih:5}}));const raw=V.makeBackup(tracking,null,'2026-09-09T00:00:00.000Z',memory);assert.equal(raw.includes('dummy-secret-should-not-export'),false);assert.equal(raw.includes('2:255'),true);const prepared=V.inspect(raw,{migrate:x=>x},'2026-09-09');assert.equal(prepared.deen.reading.bookmarks[0],'2:255');assert.equal(prepared.dhikr['2026-09-09'].tasbih,5);memory.setItem('nur-data-v1',JSON.stringify(tracking));memory.setItem('unrelated-key','keep');V.restore(memory,prepared);assert.equal(memory.getItem('unrelated-key'),'keep');assert.equal(JSON.parse(memory.getItem(D.KEY)).reading.bookmarks[0],'2:255');V.restoreRecovery(memory);assert.equal(memory.getItem('unrelated-key'),'keep');});
