const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('../web/nur-power-data.js');
const today='2026-09-09';
const blank=()=>({meta:{startedOn:'2026-09-08',persistentListsV3:true,persistentTasks:[],persistentIntentions:[]},days:{}});
function old(){const s=blank();s.days['2026-09-08']={prayers:[true,false,false,false,false],tasks:[{id:'a',title:'Study',done:true}],intentions:[{id:'i',title:'Reflect',done:true}],notes:[{id:'n',title:'Note',body:'Saved'}],money:[{id:'m',title:'Food',amount:20,type:'expense'}]};s.meta.persistentTasks=[{id:'a',title:'Study'}];s.meta.persistentIntentions=[{id:'i',title:'Reflect'}];return s;}
test('migration preserves history and creates no phantom days',()=>{const before=old(),copy=JSON.stringify(before),s=P.migrate(before,today);assert.equal(JSON.stringify(before),copy);assert.deepEqual(s.days['2026-09-08'],before.days['2026-09-08']);assert.equal(s.days[today],undefined);assert.equal(P.migrate(s,today).meta.persistentTasks[0].id,'a');});
test('daily entries persist and only completion resets',()=>{let s=P.reconcile(P.migrate(old(),today),today);assert.equal(s.days[today].tasks[0].done,false);assert.equal(s.days[today].intentions[0].done,false);s=P.toggleTask(s,'a',today);s=P.reconcile(s,'2026-09-10');assert.equal(s.days['2026-09-10'].tasks[0].done,false);assert.equal(s.days[today].tasks[0].done,true);assert.equal(s.days['2026-09-08'].tasks[0].done,true);});
test('weekdays use local calendar days including Sunday',()=>{const s=P.schedule({type:'weekdays',days:[0,1,1,9],startOn:'2026-09-09'},today);assert.deepEqual(s.days,[0,1]);const x={schedule:s};assert.equal(P.occurs(x,'2026-09-13'),true);assert.equal(P.occurs(x,'2026-09-12'),false);assert.equal(P.occurs(x,'2026-09-07'),false);});
test('one-time and bounded schedules do not repeat',()=>{const x={schedule:P.schedule({type:'once',startOn:'2026-09-10'},today)};assert.equal(P.occurs(x,today),false);assert.equal(P.occurs(x,'2026-09-10'),true);assert.equal(P.occurs(x,'2026-09-11'),false);const y={schedule:P.schedule({endOn:'2026-09-10'},today)};assert.equal(P.occurs(y,'2026-09-11'),false);});
test('schedule edits preserve completion and older snapshots',()=>{let s=P.reconcile(P.migrate(old(),today),today);s=P.toggleTask(s,'a',today);s=P.editTask(s,'a',{schedule:{type:'weekdays',days:[4],startOn:today}},today);assert.equal(s.days[today].tasks.length,0);assert.equal(s.days[today].inactiveTasks[0].done,true);s=P.editTask(s,'a',{schedule:{type:'daily',startOn:today}},today);assert.equal(s.days[today].tasks[0].done,true);assert.equal(s.days['2026-09-08'].tasks[0].done,true);});
test('deleting a definition leaves dated history intact',()=>{let s=P.reconcile(P.migrate(old(),today),today);s=P.toggleTask(s,'a',today);s=P.removeTask(s,'a',today);assert.equal(s.meta.persistentTasks.length,0);assert.equal(s.days[today].tasks.length,0);assert.equal(s.days[today].inactiveTasks[0].done,true);assert.equal(s.days['2026-09-08'].tasks[0].done,true);});
test('new and existing intentions survive the next day',()=>{let s=P.reconcile(P.migrate(old(),today),today);assert.equal(s.days[today].intentions[0].id,'i');s.days[today].intentions[0].done=true;s=P.reconcile(s,'2026-09-10');assert.equal(s.days['2026-09-10'].intentions[0].done,false);assert.equal(s.days[today].intentions[0].done,true);});
test('goals support numeric progress and independent milestones',()=>{let s=P.migrate(blank(),today);s=P.addGoal(s,{title:'Read',target:10,current:3,unit:'pages'},today);const id=s.meta.powerGoals[0].id;assert.equal(P.goalProgress(s.meta.powerGoals[0]),30);s=P.addMilestone(s,id,'First chapter');const mid=s.meta.powerGoals[0].milestones[0].id;s=P.toggleMilestone(s,id,mid);assert.equal(s.meta.powerGoals[0].milestones[0].done,true);s=P.editGoal(s,id,{current:99});assert.equal(P.goalProgress(s.meta.powerGoals[0]),100);assert.equal(s.meta.powerGoals[0].current,10);});
test('backup roundtrip preserves data and rejects unsupported versions',()=>{const s=P.migrate(old(),today),raw=P.exportData(s,{theme:'ivory'}),restored=P.validateImport(raw,today);assert.deepEqual(restored.state,s);assert.equal(restored.appearance.theme,'ivory');assert.throws(()=>P.validateImport('{"format":"nur-backup","version":9}',today));assert.throws(()=>P.migrate({...s,meta:{powerSchemaVersion:9}},today));assert.throws(()=>P.validateImport('{broken',today));});
test('invalid dates and progress are rejected',()=>{assert.equal(P.date('2026-02-31'),false);assert.throws(()=>P.addGoal(P.migrate(blank(),today),{title:'Bad',target:0,current:0},today));assert.throws(()=>P.addTask(P.migrate(blank(),today),{title:'   '},today));});
