const {test}=require('node:test');
const assert=require('node:assert/strict');
const V=require('../web/nur-vault.js');
const P=require('../web/nur-power-data.js');
const today='2026-09-09';
const sample=()=>({meta:{startedOn:'2026-09-08',persistentListsV3:true,persistentTasks:[{id:'a',title:'Study',category:'College'}],persistentIntentions:[{id:'i',title:'Reflect'}],powerGoals:[{id:'g',title:'Read',target:10,current:2,unit:'pages',milestones:[]}]},days:{'2026-09-08':{prayers:[true,false,false,false,false],tasks:[{id:'a',title:'Study',done:true}],intentions:[{id:'i',title:'Reflect',done:true}],notes:[{id:'n',title:'Note',body:'Private'}],money:[{id:'m',title:'Food',amount:20,type:'expense'}]}}});
function storage(seed={}){const data=new Map(Object.entries(seed));let fail=null;return {getItem:k=>data.has(k)?data.get(k):null,setItem(k,v){if(fail===k)throw Error('quota');data.set(k,String(v));},removeItem(k){if(fail===k)throw Error('quota');data.delete(k);},fail:k=>{fail=k;},values:()=>Object.fromEntries(data)};}
test('backup roundtrip is non-mutating and preserves dated history',()=>{const s=sample(),before=JSON.stringify(s);const raw=V.makeBackup(s,{theme:'ivory'},'2026-09-09T00:00:00.000Z');const result=V.inspect(raw,P,today);assert.equal(JSON.stringify(s),before);assert.deepEqual(result.state.days['2026-09-08'],s.days['2026-09-08']);assert.equal(result.state.days[today],undefined);assert.equal(result.summary.notes,1);assert.equal(result.summary.money,1);assert.equal(result.summary.goals,1);assert.equal(result.appearance.theme,'ivory');});
test('invalid, newer, truncated and oversized backups are rejected',()=>{const raw=V.makeBackup(sample(),null);assert.throws(()=>V.inspect('{broken',P,today));assert.throws(()=>V.inspect(JSON.stringify({...JSON.parse(raw),version:9}),P,today));assert.throws(()=>V.inspect(JSON.stringify({...JSON.parse(raw),state:{meta:{powerSchemaVersion:99},days:{}}}),P,today));assert.throws(()=>V.inspect(JSON.stringify({...JSON.parse(raw),state:{meta:{},days:{'2026-02-31':{}}}}),P,today));assert.throws(()=>V.inspect('x'.repeat(V.MAX_BYTES+1),P,today));});
test('malformed daily lists, prayers and money are rejected without coercing records',()=>{const s=sample();s.days['2026-09-08'].prayers=[true];assert.throws(()=>V.validateState(s));s.days['2026-09-08'].prayers=[true,false,false,false,false];s.days['2026-09-08'].tasks='bad';assert.throws(()=>V.validateState(s));s.days['2026-09-08'].tasks=[];s.days['2026-09-08'].money[0].amount=-3;assert.throws(()=>V.validateState(s));});
test('restore replaces only NUR data keys and retains an exact recovery copy',()=>{const old=sample(),next=sample();next.meta.persistentTasks[0].title='New study';const oldRaw=JSON.stringify(old);const db=storage({'nur-data-v1':oldRaw,'nur-first-run-date':'2026-09-08','nur-appearance-v1':'{"theme":"midnight"}','other-app-data':'keep'});const prepared=V.inspect(V.makeBackup(next,{theme:'ivory'}),P,today);V.restore(db,prepared);assert.equal(JSON.parse(db.getItem('nur-data-v1')).meta.persistentTasks[0].title,'New study');assert.equal(db.getItem('other-app-data'),'keep');assert.equal(JSON.parse(db.getItem('nur-appearance-v1')).theme,'ivory');assert.equal(V.recovery(db).values['nur-data-v1'],oldRaw);V.restoreRecovery(db);assert.equal(db.getItem('nur-data-v1'),oldRaw);assert.equal(db.getItem('nur-appearance-v1'),'{"theme":"midnight"}');});
test('storage failures do not replace data and preserve a recovery copy',()=>{const original=JSON.stringify(sample());const db=storage({'nur-data-v1':original,'nur-first-run-date':'2026-09-08'});const prepared=V.inspect(V.makeBackup(sample(),null),P,today);db.fail('nur-appearance-v1');assert.throws(()=>V.restore(db,{...prepared,appearance:{theme:'ivory'}}));assert.equal(db.getItem('nur-data-v1'),original);assert.equal(V.recovery(db).values['nur-data-v1'],original);});
test('a missing or corrupted recovery copy never overwrites current data',()=>{const db=storage({'nur-data-v1':JSON.stringify(sample())});const before=db.getItem('nur-data-v1');assert.throws(()=>V.restoreRecovery(db));db.setItem(V.KEYS.recovery,'{bad');assert.throws(()=>V.restoreRecovery(db));assert.equal(db.getItem('nur-data-v1'),before);});
