/* NUR Studio Pro — custom, offline-first appearance and layout controls. */
(function(){
'use strict';
const D=window.NurProData,A=window.NURAppearance,Assets=window.NurProAssets;
if(!D||!A||!Assets||document.querySelector('#nurProStudio'))return;
const doc=document,html=doc.documentElement,KEY=D.KEY,LAYOUT_KEY='nur-layout-presets-v1';
const el=(tag,cls,text)=>{const n=doc.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(text,cls,fn)=>{const n=el('button',cls,text);n.type='button';if(fn)n.addEventListener('click',fn);return n;};
const clone=x=>JSON.parse(JSON.stringify(x));
const baseUpdate=A.update.bind(A),baseGet=A.get.bind(A);
const BASE={
 midnight:{bg:'#030a17',surface:'#071527',card:'#0b1b30',text:'#f4f0e7',muted:'#a2afc1',line:'#32445c',accent:'#e6ad42',accentInk:'#211604',track:'#23334a',soft:'#e6ad4220'},
 ivory:{bg:'#f5f0e6',surface:'#fffaf1',card:'#fffdf8',text:'#302b25',muted:'#665e52',line:'#d4c6b2',accent:'#926319',accentInk:'#fffaf1',track:'#e0d5c4',soft:'#92631918'},
 emerald:{bg:'#041411',surface:'#0b211d',card:'#103029',text:'#e9f3ec',muted:'#a0bcb0',line:'#31584b',accent:'#8ed3ae',accentInk:'#082019',track:'#254438',soft:'#8ed3ae1d'},
 ocean:{bg:'#07111f',surface:'#0c2036',card:'#112b45',text:'#edf4fa',muted:'#a5bed0',line:'#36536b',accent:'#9dcee9',accentInk:'#082034',track:'#2a415b',soft:'#9dcee91d'},
 monochrome:{bg:'#090a0d',surface:'#15171b',card:'#1d2025',text:'#f0f0ed',muted:'#b1b3b7',line:'#40434a',accent:'#d6d8dc',accentInk:'#18191c',track:'#34363c',soft:'#d6d8dc1b'}
};
const THEMES=[['midnight','Gold & Midnight'],['ivory','Ivory & Gold'],['emerald','Emerald Night'],['ocean','Ocean & Silver'],['monochrome','Obsidian'],['amoled','AMOLED · True Black'],['system','Follow device']];
const LABELS={light:'Daily Light',prayers:'Salah',tasks:'Amanah',muhasaba:'Muhasaba',rhythm:'Rhythm',archive:'Archive',goals:'Goals',focus:'Focus Chamber',history:'History',notes:'Notes',money:'Money'};
const SYMBOLS={light:'✦',prayers:'☾',tasks:'✓',muhasaba:'◇',rhythm:'▥',archive:'▤',goals:'◎',focus:'◷',history:'▦',notes:'✎',money:'₹'};
const SELECTORS={light:'.light-panel',prayers:'.prayers-panel',tasks:'.tasks-panel',muhasaba:'.muhasaba-panel',rhythm:'.rhythm-panel',archive:'.archive-panel',goals:'#nurGoalsPanel',focus:'#nurFocusPanel'};
const media=winMatch('(prefers-color-scheme: dark)'),reduced=winMatch('(prefers-reduced-motion: reduce)');
function winMatch(query){return window.matchMedia?window.matchMedia(query):null;}
let config=D.defaults(),layouts=[],tab='appearance',previousFocus=null,message='',busy=false,applying=false,queued=false,refreshInfo='',nativeBridge=null;
try{config=D.normalize({...D.defaults(),...baseGet(),...JSON.parse(localStorage.getItem(KEY)||'{}')});}catch{config=D.defaults();}
try{const saved=JSON.parse(localStorage.getItem(LAYOUT_KEY)||'[]');if(Array.isArray(saved))layouts=saved.filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string'&&x.layout).slice(0,8);}catch{}
const frame=doc.querySelector('.dashboard-frame'),main=doc.querySelector('#nurDashboardSections');
if(!frame||!main)return;
const nodes=new Map();for(const id of D.IDS){const node=doc.querySelector(SELECTORS[id]);if(node){node.dataset.nurSection=id;nodes.set(id,node);}}
const nav=doc.querySelector('#nurSectionNav');const quick=el('nav','nur-pro-quick');quick.id='nurProQuick';quick.setAttribute('aria-label','Personal quick actions');if(nav)nav.insertAdjacentElement('afterend',quick);
const dialog=el('dialog','nur-studio nur-pro-studio');dialog.id='nurProStudio';dialog.setAttribute('aria-labelledby','nurProTitle');
const panel=el('div','nur-studio-panel');const head=el('header','nur-studio-head');const title=el('div');title.append(el('span','nur-overline','PERSONALIZE YOUR NUR'),el('h2','','Appearance Studio Pro'));title.querySelector('h2').id='nurProTitle';const closeButton=button('×','nur-studio-close',close);closeButton.setAttribute('aria-label','Close Appearance Studio');head.append(title,closeButton);
const tabs=el('nav','nur-pro-tabs');tabs.setAttribute('aria-label','Studio sections');const content=el('div','nur-studio-content nur-pro-content');const status=el('p','nur-studio-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const actions=el('div','nur-studio-actions');const reset=button('Restore visual defaults','nur-tool-button nur-tool-subtle',()=>{if(!window.confirm('Restore the original NUR appearance and layout? Your tracking data and imported files will remain saved.'))return;baseUpdate({theme:'midnight',background:'artwork',fontScale:1,motion:'system',density:'comfortable',order:['light','prayers','tasks','muhasaba','rhythm','archive'],hidden:[]});set(D.defaults(),'Original appearance restored.');});actions.append(reset,button('Done','nur-primary-button',close));panel.append(head,tabs,content,status,actions);dialog.append(panel);doc.body.append(dialog);
function say(text){message=text;status.textContent=text;}
function motionOff(){return config.motion==='reduced'||!!reduced?.matches;}
const canonical=()=>{const b=baseGet(),name=b.theme==='system'?(media?.matches?'midnight':'ivory'):b.theme;return BASE[name]||BASE.midnight;};
function theme(){return config.theme==='amoled'?{bg:'#000000',surface:'#000000',card:'#000000',text:'#ffffff',muted:'#b8b8b8',line:'#343434',accent:'#e6ad42',accentInk:'#211604',track:'#242424',soft:'#e6ad4220'}:canonical();}
function nodeFor(id){return nodes.get(id)||doc.querySelector(SELECTORS[id]);}
function reorder(){
 for(const [i,id] of config.order.entries()){const node=nodeFor(id);if(!node)continue;const current=main.children[i]||null;if(current!==node)main.insertBefore(node,current);}
 for(const id of D.IDS){const node=nodeFor(id);if(!node)continue;node.hidden=config.hidden.includes(id);node.dataset.nurSize=config.sizes[id]||'normal';}
}
function refreshNavigation(){
 if(nav){nav.replaceChildren();for(const id of config.order){if(config.hidden.includes(id)||!nodeFor(id))continue;const b=button(SYMBOLS[id]+'  '+LABELS[id],'nur-nav-item',()=>navigate(id));b.dataset.nurTarget=id;nav.append(b);}nav.append(button('⋯  Customize','nur-nav-item nur-nav-more',()=>open('layout')));}
 quick.replaceChildren();for(const id of config.quick){const b=button(SYMBOLS[id]+'  '+LABELS[id],'nur-pro-quick-item',()=>navigate(id));b.dataset.nurQuick=id;quick.append(b);}quick.hidden=!config.quick.length;
}
function apply(){
 if(applying)return;applying=true;
 try{
  const p=theme();for(const [name,value] of Object.entries(p))html.style.setProperty('--nur-'+name.replace(/[A-Z]/g,x=>'-'+x.toLowerCase()),value);
  if(config.accent){html.style.setProperty('--nur-accent',config.accent);html.style.setProperty('--nur-accent-ink',D.ink(config.accent));html.style.setProperty('--nur-soft',config.accent+'20');}
  html.dataset.nurProAmoled=String(config.theme==='amoled');html.dataset.nurProBg=config.background;html.dataset.nurProFont=config.font;html.dataset.nurProMotion=motionOff()?'reduced':'full';
  html.style.setProperty('--nur-pro-radius',config.radius+'px');html.style.setProperty('--nur-pro-blur',config.blur+'px');html.style.setProperty('--nur-pro-shadow-alpha',String(.12*config.shadow));html.style.setProperty('--nur-font-scale',String(config.fontScale));html.style.setProperty('--nur-gap',config.density==='compact'?'8px':config.density==='spacious'?'20px':'11px');
  html.style.setProperty('--nur-duration',motionOff()?'0ms':Math.round(400/config.motionSpeed)+'ms');html.style.setProperty('--progress-time',motionOff()?'0ms':Math.round(500/config.motionSpeed)+'ms');html.style.setProperty('--nur-pro-speed',motionOff()?'0ms':Math.round(450/config.motionSpeed)+'ms');
  html.style.setProperty('--nur-ui-font',config.font==='serif'?'Georgia,serif':config.font==='sans'?'system-ui,sans-serif':config.font==='custom'?'var(--nur-custom-font,system-ui,sans-serif)':'var(--sans)');
  const meta=doc.querySelector('meta[name="theme-color"]');if(meta)meta.content=p.bg;
  reorder();refreshNavigation();window.NURProgress?.configure(config);
  const journey=doc.querySelector('#nurJourney .nur-journey-action');if(journey){const text=journey.textContent;const target=text.includes('Amanah')?'tasks':text.includes('Muhasaba')?'muhasaba':text.includes('Daily Light')?'light':'prayers';journey.onclick=()=>navigate(target);}
 }finally{applying=false;}
}
function set(patch,note){
 const next=D.normalize({...config,...patch});
 try{localStorage.setItem(KEY,JSON.stringify(next));}catch{say('Unable to save appearance settings. Your previous settings remain active.');return false;}
 config=next;
 const b=baseGet();if(b.density!==config.density||b.fontScale!==config.fontScale||b.motion!==config.motion)baseUpdate({density:config.density,fontScale:config.fontScale,motion:config.motion});
 apply();if(note)say(note);if(dialog.open)draw();return true;
}
function setTheme(value){
 if(value==='amoled'){set({theme:'amoled'},'AMOLED black selected.');return;}
 if(!baseUpdate({theme:value},'Theme selected.')){say('Unable to save the theme.');return;}
 set({theme:'inherit'},'Theme selected.');
}
function navigate(id){
 if(['history','notes','money'].includes(id)){window.openModal?.(id);return;}
 if(id==='focus'){window.NURFocusUI?.open();return;}
 if(id==='goals'){window.NURPowerUI?.open('goals');return;}
 if(id==='tasks'){window.NURPowerUI?.open('tasks');return;}
 if(id==='muhasaba'){window.openModal?.('muhasaba');return;}
 if(id==='prayers'){window.openModal?.('prayers');return;}
 if(config.hidden.includes(id))set({hidden:config.hidden.filter(x=>x!==id)},'Section restored.');
 const node=nodeFor(id);node?.scrollIntoView?.({behavior:motionOff()?'instant':'smooth',block:'start'});
}
function open(nextTab='appearance'){tab=nextTab;previousFocus=doc.activeElement;draw();if(!dialog.open){if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}closeButton.focus();}
function close(){if(dialog.open&&dialog.close)dialog.close();else dialog.removeAttribute('open');previousFocus?.focus?.();previousFocus=null;}
dialog.addEventListener('click',e=>{if(e.target===dialog)close();});dialog.addEventListener('close',()=>{previousFocus?.focus?.();previousFocus=null;});
function section(title,description){const n=el('section','nur-pro-setting-section');n.append(el('h3','',title));if(description)n.append(el('p','nur-setting-help',description));return n;}
function select(title,description,value,options,onChange){const wrap=el('label','nur-setting'),caption=el('span','nur-setting-caption');caption.append(el('strong','',title),el('small','',description));const field=el('select','nur-select');for(const [v,label] of options){const o=el('option','',label);o.value=v;field.append(o);}field.value=String(value);field.addEventListener('change',()=>onChange(field.value));wrap.append(caption,field);return wrap;}
function range(title,description,value,min,max,step,suffix,onChange){const wrap=el('label','nur-setting'),caption=el('span','nur-setting-caption');caption.append(el('strong','',title),el('small','',description));const input=el('input','nur-range');input.type='range';input.min=min;input.max=max;input.step=step;input.value=value;const label=el('span','nur-range-value',value+suffix);input.addEventListener('input',()=>{label.textContent=input.value+suffix;});input.addEventListener('change',()=>onChange(Number(input.value)));wrap.append(caption,input,label);return wrap;}
function toggle(title,description,checked,onChange){const row=el('label','nur-pro-switch'),copy=el('span','nur-setting-caption');copy.append(el('strong','',title),el('small','',description));const input=el('input');input.type='checkbox';input.checked=checked;input.addEventListener('change',()=>onChange(input.checked));row.append(copy,input);return row;}
function actionsRow(...items){const row=el('div','nur-power-actions');row.append(...items);return row;}
function draw(){
 tabs.replaceChildren();content.replaceChildren();status.textContent=message;
 for(const [id,name] of [['appearance','Appearance'],['progress','Progress'],['motion','Motion'],['layout','Layout'],['assets','My assets']]){const b=button(name,'nur-studio-tab',()=>{tab=id;draw();});b.setAttribute('aria-current',String(tab===id));tabs.append(b);}
 if(tab==='appearance')drawAppearance();else if(tab==='progress')drawProgress();else if(tab==='motion')drawMotion();else if(tab==='layout')drawLayout();else drawAssets();
}
function drawAppearance(){
 const root=section('Signature themes','Choose a complete palette. The Arabic NUR identity and golden Daily Light remain preserved.');
 const grid=el('div','nur-theme-grid');for(const [id,name] of THEMES){const b=button('','nur-theme-choice',()=>setTheme(id)),p=id==='amoled'?theme():id==='system'?(media?.matches?BASE.midnight:BASE.ivory):BASE[id];b.style.setProperty('--swatch-bg',p.bg);b.style.setProperty('--swatch-surface',p.surface);b.style.setProperty('--swatch-accent',p.accent);b.setAttribute('aria-pressed',String(id==='amoled'?config.theme==='amoled':config.theme!=='amoled'&&baseGet().theme===id));const sample=el('span','nur-theme-sample');sample.append(el('span','nur-theme-sun','✦'),el('span','nur-theme-sample-line'),el('span','nur-theme-sample-line short'));b.append(sample,el('strong','',name));grid.append(b);}root.append(grid);content.append(root);
 const colors=section('Personal color','The custom accent changes controls and selection. Signature gold is retained.');const row=el('div','nur-pro-color-row');const color=el('input');color.type='color';color.value=config.accent||'#e6ad42';color.setAttribute('aria-label','Custom accent color');color.addEventListener('change',()=>set({accent:color.value},'Accent saved.'));row.append(color,button('Use custom accent','nur-power-small',()=>set({accent:color.value},'Accent saved.')),button('Restore palette color','nur-power-small',()=>set({accent:null},'Palette accent restored.')));colors.append(row);content.append(colors);
 const look=section('Surfaces','Refine the shape and depth of NUR without changing its content.');look.append(range('Corner radius','Roundness of cards and dialogs.',config.radius,8,32,1,' px',v=>set({radius:v})),range('Shadow depth','Adjust surface elevation from flat to soft.',config.shadow,0,2,.1,'×',v=>set({shadow:v})),select('Background','Original artwork, a quiet surface, or your own wallpaper.',config.background,[['inherit','Original artwork'],['none','Quiet surface'],['custom','Custom wallpaper']],v=>set({background:v})),range('Background blur','Softens your selected wallpaper.',config.blur,0,24,1,' px',v=>set({blur:v})));content.append(look);
 const type=section('Typography','Imported fonts change the interface, not the Arabic calligraphy.');type.append(select('Font style','Use a built-in family or your imported font.',config.font,[['system','Original NUR'],['sans','Modern sans'],['serif','Editorial serif'],['custom','Imported font']],v=>{if(v==='custom'&&!config.fontName){tab='assets';draw();say('Import a font first.');return;}set({font:v});}),range('Text size','Scale interface text while preserving Arabic proportions.',config.fontScale,.9,1.25,.05,'×',v=>set({fontScale:v})),select('Card spacing','Choose a compact or relaxed layout.',config.density,[['compact','Compact'],['comfortable','Comfortable'],['spacious','Spacious']],v=>set({density:v})));const sample=el('div','nur-pro-type-sample');sample.append(el('strong','','A day, with intention'),el('p','','A quieter space for your daily responsibilities.'));type.append(sample,button('Import a font or wallpaper ↗','nur-tool-button',()=>{tab='assets';draw();}));content.append(type);
}
function drawProgress(){
 content.append(el('p','nur-setting-help','Choose a separate progression style for each section. These settings change appearance only; completion values and history remain unchanged.'));
 for(const id of D.TARGETS){const s=config.progress[id],block=section(LABELS[id]||id,'Choose the shape, thickness and glow.');const preview=el('div','nur-pro-progress-preview');preview.dataset.nurPreview=id;preview.setAttribute('aria-label','Sample progression at 65 percent');block.append(preview);
 block.append(select('Progression style','Classic, slim, thick, wavy, squiggly, segmented or liquid.',s.style,D.STYLES.map(x=>[x,x[0].toUpperCase()+x.slice(1)]),v=>set({progress:{...config.progress,[id]:{...s,style:v}}})),range('Thickness','Stroke width of the chosen indicator.',s.thickness,2,20,1,' px',v=>set({progress:{...config.progress,[id]:{...s,thickness:v}}})),range('Glow','A restrained glow around the completed portion.',s.glow,0,16,1,' px',v=>set({progress:{...config.progress,[id]:{...s,glow:v}}})));content.append(block);renderPreview(preview,id);
 }
 content.append(el('p','nur-setting-help','The original loader and four-star Allah ring remain intact. Progress animations respect reduced-motion preferences.'));
}
function renderPreview(node,id){const s=config.progress[id],ns='http://www.w3.org/2000/svg',make=(tag,attrs)=>{const n=doc.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));return n;};const picture=make('svg',{viewBox:'0 0 100 100',preserveAspectRatio:'none','aria-hidden':'true'}),d=['light','muhasaba'].includes(id)?D.ring(s.style):D.geometry(s.style,65).path;const track=make('path',{d,fill:'none',stroke:'var(--nur-track)','stroke-width':s.thickness/2,pathLength:100}),fill=make('path',{d,fill:'none',stroke:'var(--nur-accent)','stroke-width':s.thickness/2,pathLength:100,'stroke-dasharray':'65 35','stroke-linecap':'round'});picture.append(track,fill);node.append(picture,el('span','','65%'));}
async function bridge(){if(nativeBridge)return nativeBridge;const cap=window.Capacitor;if(!cap?.isNativePlatform?.()||!cap.registerPlugin||cap.isPluginAvailable&&!cap.isPluginAvailable('NurExperience'))throw Error('Native display controls are available only in the supported Android build.');nativeBridge=cap.registerPlugin('NurExperience');return nativeBridge;}
async function refreshModes(){try{const plugin=await bridge(),info=await plugin.getDisplayModes();refreshInfo='Supported modes: '+info.modes.map(x=>Math.round(x.refreshRate)+' Hz').join(', ')+'. Current: '+Math.round(info.currentRefreshRate)+' Hz.';}catch(e){refreshInfo=e.message;}if(dialog.open&&tab==='motion')draw();}
async function requestRefresh(value){const previous=config.refresh;try{const plugin=await bridge(),result=await plugin.setRefreshRate({mode:value});if(!set({refresh:value},value==='high'?'Requested '+Math.round(result.requestedRefreshRate)+' Hz. Android may adjust the actual rate.':'System refresh-rate preference restored.')){await plugin.setRefreshRate({mode:previous});}}catch(e){say(e.message||'Display mode could not be changed.');}}
function drawMotion(){
 const motion=section('Motion & feedback','Smooth transitions where useful, with reduced-motion support and no unrelated card reanimations.');motion.append(select('Animation mode','Follow the device, use expressive motion, or reduce animations.',config.motion,[['system','Follow device'],['full','Expressive'],['reduced','Reduced']],v=>set({motion:v})),range('Motion speed','Adjust the speed of transitions and progress fills.',config.motionSpeed,.5,2,.1,'×',v=>set({motionSpeed:v})),toggle('Touch haptics','Subtle vibration on supported devices.',config.haptics,v=>set({haptics:v})));content.append(motion);
 const display=section('Display refresh rate','Request the highest supported display mode. Android may limit the rate for battery, temperature or system policy.');display.append(select('Refresh preference','This option cannot force an unsupported refresh rate.',config.refresh,[['system','Follow Android'],['high','Highest supported mode']],v=>requestRefresh(v)),button('Check supported display modes','nur-tool-button',refreshModes));display.append(el('p','nur-setting-help',refreshInfo||'Tap to inspect supported modes on your Android device. Web previews cannot change display modes.'));content.append(display);
}
function layoutSnapshot(){return {order:config.order,hidden:config.hidden,sizes:config.sizes,quick:config.quick};}
function saveLayouts(next){const values=clone(next).slice(0,8);try{localStorage.setItem(LAYOUT_KEY,JSON.stringify(values));layouts=values;return true;}catch{say('Unable to save layouts.');return false;}}
function applyLayout(layout,note){set({...layout,preset:'original'},note);}
function drawLayout(){
 const presets=section('Dashboard presets','Switch layouts without losing any personal records or visual settings.');const grid=el('div','nur-pro-preset-grid');for(const [id,p] of Object.entries(D.PRESETS)){const b=button(p.name,'nur-pro-preset',()=>set(D.preset(config,id),p.name+' layout applied.'));b.setAttribute('aria-pressed',String(config.preset===id));grid.append(b);}presets.append(grid);content.append(presets);
 const saved=section('My saved layouts','Save and restore your own section arrangements.');const name=el('input','nur-power-input');name.placeholder='Layout name';name.maxLength=50;name.setAttribute('aria-label','New layout name');saved.append(actionsRow(name,button('Save layout','nur-power-small',()=>{const title=name.value.trim();if(!title){say('Enter a layout name.');return;}const next=[...layouts,{id:window.crypto?.randomUUID?.()||String(Date.now()),name:title,layout:clone(layoutSnapshot())}];if(saveLayouts(next)){say('Layout saved.');draw();}})));
 for(const item of layouts){const row=el('div','nur-pro-layout-row');row.append(el('strong','',item.name),button('Apply','nur-power-small',()=>applyLayout(item.layout,item.name+' restored.')),button('Delete','nur-power-danger',()=>{if(window.confirm('Delete this saved layout?')){saveLayouts(layouts.filter(x=>x.id!==item.id));draw();}}));saved.append(row);}content.append(saved);
 const order=section('Arrange your cards','Move sections with the arrows, choose sizes and hide unused cards. Hidden cards remain available in the builder.');
 for(const [index,id] of config.order.entries()){const row=el('div','nur-pro-layout-row'),info=el('div','nur-power-row-copy');info.append(el('strong','',SYMBOLS[id]+'  '+LABELS[id]));const controls=el('div','nur-pro-layout-controls');const up=button('↑','nur-mini-button',()=>set({order:D.move(config.order,id,-1),preset:'original'}));up.disabled=index===0;up.setAttribute('aria-label','Move '+LABELS[id]+' up');const down=button('↓','nur-mini-button',()=>set({order:D.move(config.order,id,1),preset:'original'}));down.disabled=index===config.order.length-1;down.setAttribute('aria-label','Move '+LABELS[id]+' down');const size=el('select','nur-select');size.setAttribute('aria-label',LABELS[id]+' card size');for(const [v,text] of [['compact','Compact'],['normal','Normal'],['wide','Wide'],['hero','Hero']]){const option=el('option','',text);option.value=v;size.append(option);}size.value=config.sizes[id]||'normal';size.addEventListener('change',()=>set({sizes:{...config.sizes,[id]:size.value},preset:'original'}));const show=el('input');show.type='checkbox';show.checked=!config.hidden.includes(id);show.disabled=id==='light';show.setAttribute('aria-label','Show '+LABELS[id]);show.addEventListener('change',()=>set({hidden:show.checked?config.hidden.filter(x=>x!==id):[...config.hidden,id],preset:'original'}));controls.append(up,down,size,show);row.append(info,controls);order.append(row);}order.append(button('Show all sections','nur-tool-button',()=>set({hidden:[],preset:'original'},'All sections restored.')));content.append(order);
 const quickSection=section('Quick actions','Choose up to five shortcuts for your dashboard.');for(const id of ['prayers','tasks','muhasaba','focus','goals','history','notes','money','light']){const checked=config.quick.includes(id);quickSection.append(toggle(LABELS[id],'Show in quick actions.',checked,v=>{const next=v?[...config.quick,id]:config.quick.filter(x=>x!==id);if(next.length>5){say('Choose up to five quick actions.');return;}set({quick:next,preset:'original'});}));}content.append(quickSection);
}
async function fileAction(kind,file){if(!file)return;busy=true;say('Checking the selected file…');let result=null;try{result=await Assets.save(file,kind);const patch=kind==='font'?{font:'custom',fontName:result.record.name}:{background:'custom'};if(!set(patch,'Imported '+kind+' saved on this device.'))throw Error('Appearance settings could not be saved.');}catch(e){if(result)try{await Assets.rollback(kind,result.before);}catch{}say(e.message||'Unable to import this file.');}finally{busy=false;}}
function filePicker(kind){const label=el('label','nur-pro-file'),text=el('span','',kind==='font'?'Import a font':'Import a wallpaper'),input=el('input');input.type='file';input.accept=kind==='font'?'.ttf,.otf,.woff,.woff2':'image/png,image/jpeg,image/webp';input.setAttribute('aria-label',kind==='font'?'Choose a font file':'Choose a wallpaper image');input.addEventListener('change',async()=>{if(input.files?.[0])await fileAction(kind,input.files[0]);});label.append(text,input);return label;}
async function shareText(raw,name){const cap=window.Capacitor;if(cap?.isNativePlatform?.()&&cap.registerPlugin){const fs=cap.registerPlugin('Filesystem'),share=cap.registerPlugin('Share'),bytes=new TextEncoder().encode(raw);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const saved=await fs.writeFile({path:name,data:btoa(binary),directory:'CACHE'});await share.share({title:'NUR appearance',url:saved.uri,dialogTitle:'Save appearance'});return;}
 const file=new File([raw],name,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'NUR appearance'});return;}const url=URL.createObjectURL(file),a=el('a');a.href=url;a.download=name;doc.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
async function exportAppearance(){try{busy=true;const raw=await Assets.exportBundle(config,layouts);await shareText(raw,'NUR-appearance-'+new Date().toISOString().slice(0,10)+'.json');say('Appearance file prepared. Keep it private.');}catch(e){say(e.message||'Appearance export failed.');}finally{busy=false;}}
async function importAppearance(file){if(!file)return;try{busy=true;say('Validating appearance file…');const prepared=Assets.inspectBundle(await file.text());if(!window.confirm('Replace your current appearance and saved layouts? Tracking data will not be changed.'))return;const previous={config:clone(config),layouts:clone(layouts),font:await Assets.get('font'),background:await Assets.get('background')};try{for(const asset of prepared.assets)await Assets.put(asset);for(const asset of prepared.assets)await Assets.activate(asset);if(!saveLayouts(prepared.layouts))throw Error('Unable to save imported layouts.');if(!set(prepared.config,'Appearance imported.'))throw Error('Unable to save imported appearance.');}catch(e){await Assets.rollback('font',previous.font);await Assets.rollback('background',previous.background);saveLayouts(previous.layouts);set(previous.config);throw e;}}catch(e){say(e.message||'Appearance import failed.');}finally{busy=false;}}
function drawAssets(){
 const fonts=section('Custom typography','Import a local TTF, OTF, WOFF or WOFF2 font (maximum 5 MB). The font is stored only on this device.');fonts.append(filePicker('font'),el('p','nur-setting-help',config.fontName?'Current font: '+config.fontName:'No imported font selected.'));fonts.append(actionsRow(button('Use imported font','nur-power-small',()=>{if(config.fontName)set({font:'custom'});else say('Import a font first.');}),button('Remove imported font','nur-power-danger',async()=>{if(!window.confirm('Remove the imported font from this device?'))return;if(set({font:'system',fontName:null})){Assets.unload('font');try{await Assets.remove('font');say('Imported font removed.');}catch(e){say(e.message);}}})));content.append(fonts);
 const backgrounds=section('Personal wallpaper','Import PNG, JPEG or WebP, up to 8 MB. Large or invalid images are rejected before replacing your wallpaper.');backgrounds.append(filePicker('background'),range('Wallpaper blur','Keep your text readable over the image.',config.blur,0,24,1,' px',v=>set({blur:v})));backgrounds.append(actionsRow(button('Use wallpaper','nur-power-small',async()=>{try{await Assets.load('background');set({background:'custom'});}catch(e){say(e.message);}}),button('Remove wallpaper','nur-power-danger',async()=>{if(!window.confirm('Remove your imported wallpaper?'))return;if(set({background:'inherit'})){Assets.unload('background');try{await Assets.remove('background');say('Wallpaper removed.');}catch(e){say(e.message);}}})));content.append(backgrounds);
 const bundle=section('Appearance backup','Export or import your visual settings and imported files. This is separate from your personal tracking backup.');bundle.append(button('Export appearance bundle','nur-power-primary',exportAppearance));const input=el('input','nur-power-input');input.type='file';input.accept='.json,application/json';input.setAttribute('aria-label','Import NUR appearance file');input.addEventListener('change',()=>{if(input.files?.[0])importAppearance(input.files[0]);});bundle.append(input);content.append(bundle);
}
function replaceLaunchers(){const tools=doc.querySelector('.nur-experience-tools');if(!tools)return;for(const old of [...tools.children]){if(old.textContent.includes('Appearance')||old.textContent.trim()==='Customize'){const next=old.cloneNode(true);next.textContent=old.textContent.includes('Appearance')?'✧  Appearance Pro':'Customize';next.addEventListener('click',()=>open(old.textContent.includes('Appearance')?'appearance':'layout'));old.replaceWith(next);}}}
replaceLaunchers();A.open=open;A.navigate=navigate;A.update=function(patch,note){const ok=baseUpdate(patch,note);if(ok)apply();return ok;};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function nurProRender(){const result=oldRender.apply(this,arguments);apply();return result;};
const oldVibrate=window.vibrate;if(typeof oldVibrate==='function')window.vibrate=function(ms){if(config.haptics&&!motionOff())return oldVibrate(Math.min(Number(ms)||12,45));};
for(const mq of [media,reduced])mq?.addEventListener?.('change',apply);
window.addEventListener('storage',e=>{if(e.key===KEY){try{config=D.normalize(JSON.parse(e.newValue||'null'));apply();if(dialog.open)draw();}catch{}}else if(e.key===A.KEY)apply();});
window.addEventListener('focus',()=>{if(config.refresh==='high')requestRefresh('high');});
function initAssets(){Promise.allSettled(['font','background'].map(async kind=>{if(kind==='font'&&config.font!=='custom'||kind==='background'&&config.background!=='custom')return;await Assets.load(kind);})).then(results=>{for(const r of results)if(r.status==='rejected')say(r.reason.message);apply();});}
const vault=doc.querySelector('#nurVault .nur-power-shell');if(vault){const note=el('p','nur-pro-vault-note','Imported fonts and wallpapers are stored separately on this device. Export an Appearance Bundle to preserve them before uninstalling or clearing app data.');note.append(button('Open appearance export ↗','nur-power-small',()=>{window.NURVaultUI?.close();open('assets');}));vault.append(note);}
window.NURPro={get:()=>D.normalize(config),set,open,navigate,apply,loadPreset:id=>set(D.preset(config,id)),getLayouts:()=>clone(layouts),getNativeInfo:refreshModes};
apply();initAssets();
})();