/* NUR Deen Companion — custom interface, source-aware and opt-in networking. */
(function(){
'use strict';
const D=window.NurDeenCore,C=window.NurDeenContent,S=window.NurAISecrets;
if(!D||!C||!S||document.querySelector('#nurDeenDialog'))return;
const doc=document,el=(tag,cls,text)=>{const n=doc.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(label,cls,fn)=>{const n=el('button',cls,label);n.type='button';if(fn)n.addEventListener('click',fn);return n;};
const field=(label,value='',type='text')=>{const l=el('label','nur-deen-field');l.append(el('span','',label));const i=el('input','nur-power-input');i.type=type;i.value=String(value??'');l.append(i);return {wrap:l,input:i};};
const select=(label,options,value)=>{const l=el('label','nur-deen-field');l.append(el('span','',label));const s=el('select','nur-power-input');for(const [v,t] of options){const o=el('option','',t);o.value=v;s.append(o);}s.value=value;l.append(s);return {wrap:l,input:s};};
const checkbox=(label,checked,fn)=>{const l=el('label','nur-deen-check'),i=el('input');i.type='checkbox';i.checked=checked;i.addEventListener('change',()=>fn(i.checked));l.append(i,el('span','',label));return l;};
const link=(label,url)=>{const a=el('a','nur-deen-link',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;};
const row=(...children)=>{const n=el('div','nur-deen-row');n.append(...children);return n;};
const note=text=>el('p','nur-power-help',text);
const clone=x=>JSON.parse(JSON.stringify(x));
const store=S.createStore();
let data=D.empty(),tab='reading',chapter=1,page=0,corpus={},active=null,previousFocus=null,busy=false,controller=null,modelOptions=[],message='',searchQuery='',selectedReference=null,prayerTable=null,dhikr={};
try{data=D.normalize(JSON.parse(localStorage.getItem(D.KEY)||'null'));}catch{data=D.empty();}
try{const v=JSON.parse(localStorage.getItem('nur-dhikr-v1')||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))dhikr=v;}catch{}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function save(next){const normalized=D.normalize(next);localStorage.setItem(D.KEY,JSON.stringify(normalized));data=normalized;return true;}
function change(fn){try{const n=D.mutate(data,fn);save(n);return true;}catch(e){say(e.message||'Unable to save. Previous data is unchanged.');return false;}}
function say(value){message=value;status.textContent=value;}
function fail(error){say(error?.name==='AbortError'?'Request cancelled.':error?.message||'The operation could not be completed.');}
async function run(fn){if(busy)return;busy=true;draw();try{await fn();}catch(e){fail(e);}finally{busy=false;draw();}}
const frame=doc.querySelector('.dashboard-frame');if(!frame)return;
const cards=el('div','nur-deen-cards');cards.id='nurDeenCards';
for(const [id,title,subtitle,summary] of [['reading','Quran & Dhikr','Read with reflection','An attributed reader with private bookmarks.'],['prayer','Prayer companion','Your daily timetable','Calculated times, local corrections and reminders.'],['ai','NUR AI','Ask, learn and reflect','Optional Gemini integration with your own API key.']]){
 const card=el('article','panel nur-deen-card');card.dataset.deenCard=id;card.append(el('span','eyebrow',subtitle),el('h2','',title),el('p','nur-power-help',summary),button('Open '+title+' ↗','nur-power-small',()=>open(id)));cards.append(card);
}
frame.insertBefore(cards,frame.querySelector('.frame-foot'));
const dialog=el('dialog','nur-power-dialog nur-deen-dialog');dialog.id='nurDeenDialog';dialog.setAttribute('aria-labelledby','nurDeenTitle');const shell=el('div','nur-power-shell');
const head=el('header','nur-power-head'),heading=el('div');heading.append(el('span','eyebrow','NUR · DEEN COMPANION'),el('h2','','Quran & Dhikr'));heading.querySelector('h2').id='nurDeenTitle';const closeButton=button('×','nur-power-close',close);closeButton.setAttribute('aria-label','Close Deen companion');head.append(heading,closeButton);
const tabs=el('nav','nur-deen-tabs');tabs.setAttribute('aria-label','Deen companion sections');const content=el('div','nur-power-content nur-deen-content'),status=el('p','nur-power-notice');status.setAttribute('role','status');status.setAttribute('aria-live','polite');shell.append(head,tabs,content,status);dialog.append(shell);doc.body.append(dialog);
function open(next='reading'){tab=next;previousFocus=doc.activeElement;draw();if(!dialog.open){if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}closeButton.focus();}
function close(){if(dialog.open&&dialog.close)dialog.close();else dialog.removeAttribute('open');previousFocus?.focus?.();previousFocus=null;}
dialog.addEventListener('click',e=>{if(e.target===dialog)close();});dialog.addEventListener('close',()=>{previousFocus?.focus?.();previousFocus=null;});
function draw(){tabs.replaceChildren();content.replaceChildren();status.textContent=message;heading.querySelector('h2').textContent={reading:'Quran & Dhikr',prayer:'Prayer companion',ai:'NUR AI'}[tab];for(const [id,label] of [['reading','Quran & Dhikr'],['prayer','Prayer times'],['ai','NUR AI']]){const b=button(label,'nur-power-tab',()=>{tab=id;message='';draw();});b.setAttribute('aria-current',String(tab===id));tabs.append(b);}if(tab==='reading')drawReading();else if(tab==='prayer')drawPrayer();else drawAI();}
/* Quran text is fetched verbatim from the selected edition and cached separately from user data. */
const CACHE_DB='nur-quran-content-v1';
function cacheDb(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('Offline content storage is unavailable.'));const r=indexedDB.open(CACHE_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('editions'))r.result.createObjectStore('editions');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Offline content storage is unavailable.'));});}
async function cache(action,key,value){const db=await cacheDb();return new Promise((resolve,reject)=>{const tx=db.transaction('editions',action==='get'?'readonly':'readwrite'),s=tx.objectStore('editions');const r=action==='get'?s.get(key):s.put(value,key);let result;r.onsuccess=()=>result=r.result;r.onerror=()=>reject(Error('Content cache failed.'));tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(Error('Content cache failed.'));};});}
async function api(path,signal){const r=await fetch(C.API+path,{signal});if(!r.ok)throw Error('Quran service unavailable. HTTP '+r.status+'.');const raw=await r.text();if(raw.length>8_000_000)throw Error('Quran response exceeds the size limit.');return JSON.parse(raw);}
async function loadCorpus(edition){if(corpus[edition])return corpus[edition];const saved=await cache('get','full:'+edition).catch(()=>null);if(saved){corpus[edition]=saved;return saved;}return null;}
async function fetchChapter(id,edition,signal){const full=await loadCorpus(edition);if(full)return full[id-1];const key='chapter:'+id+':'+edition;const saved=await cache('get',key).catch(()=>null);if(saved)return saved;const result=D.validateChapter(await api('/surah/'+id+'/'+encodeURIComponent(edition),signal),id,edition);await cache('put',key,result).catch(()=>{});return result;}
async function fullDownload(edition){await run(async()=>{say('Downloading and validating all 114 chapters…');const raw=await api('/quran/'+encodeURIComponent(edition));const checked=C.validateCorpus(raw,edition);await cache('put','full:'+edition,checked);corpus[edition]=checked;say('Complete '+(edition==='quran-uthmani'?'Arabic':'translation')+' edition saved for offline reading.');});}
async function loadReading(id=chapter){await run(async()=>{chapter=id;page=0;active=await fetchChapter(id,'quran-uthmani');if(data.reading.showTranslation&&data.reading.translation!=='none')active.translation=await fetchChapter(id,data.reading.translation);say('Chapter loaded.');});}
async function loadVerse(key){const [s,n]=key.split(':').map(Number);const a=await fetchChapter(s,'quran-uthmani');const translation=data.reading.translation==='none'?null:await fetchChapter(s,data.reading.translation);return {key,arabic:a.verses[n-1]?.text||'',translation:translation?.verses[n-1]?.text||'',source:translation?.editionName||''};}
function verseCard(v,translation){const box=el('article','nur-deen-verse');box.append(el('span','nur-deen-ref',v.key),el('p','nur-deen-arabic',v.text));const t=translation?.verses?.find(x=>x.key===v.key);if(t&&data.reading.showTranslation)box.append(el('p','nur-deen-translation',t.text));const actions=row();const bookmarked=data.reading.bookmarks.includes(v.key),read=data.reading.read.includes(v.key);actions.append(button(bookmarked?'★ Bookmarked':'☆ Bookmark','nur-power-small',()=>{if(change(s=>{s.reading=D.reading(s,v.key,'bookmark').reading;}))draw();}),button(read?'✓ Read':'Mark read','nur-power-small',()=>{if(change(s=>{s.reading=D.reading(s,v.key,'read').reading;}))draw();}),button('Use in NUR AI','nur-power-small',()=>{selectedReference=v.key;tab='ai';draw();}));box.append(actions);return box;}
function drawReading(){const r=data.reading;const controls=row();const surah=select('Surah',C.NAMES.map((n,i)=>[String(i+1),(i+1)+'. '+n]),String(chapter));surah.input.addEventListener('change',()=>loadReading(Number(surah.input.value)));const tr=select('Translation',[['none','Arabic only'],...Object.entries(C.EDITIONS).filter(([k])=>k!=='arabic').map(([k,v])=>[k,v.label])],r.translation);tr.input.addEventListener('change',()=>{change(s=>{s.reading.translation=tr.input.value;s.reading.showTranslation=tr.input.value!=='none';});active=null;loadReading();});controls.append(surah.wrap,tr.wrap);content.append(controls);
 content.append(row(button('Load chapter','nur-power-small',()=>loadReading(),),button('Download full Arabic','nur-power-small',()=>fullDownload('quran-uthmani')),button('Download selected translation','nur-power-small',()=>fullDownload(r.translation==='none'?'en.sahih':r.translation))));
 content.append(note('Full editions are validated against the 114-surah, 6,236-verse structure. Downloads are optional and can be read offline. Arabic: AlQuran.Cloud Uthmani edition. Translations remain separately attributed.'));
 if(r.last)content.append(row(el('span','nur-power-help','Last position: '+r.last),button('Resume ↗','nur-power-small',()=>{const s=Number(r.last.split(':')[0]);loadReading(s).then(()=>{page=Math.floor((Number(r.last.split(':')[1])-1)/20);draw();});})));
 const searchInput=field('Search downloaded Arabic or translation','');searchInput.input.value=searchQuery;const searchButton=button('Search','nur-power-small',()=>{searchQuery=searchInput.input.value.trim();draw();});content.append(row(searchInput.wrap,searchButton));
 if(searchQuery){const results=[];for(const edition of Object.values(corpus))for(const ch of edition)results.push(...D.search(ch.verses,searchQuery).map(v=>({...v,edition:ch.edition})));content.append(note(results.length?'Matches in downloaded editions:':'No matches in downloaded editions. Download the full text to search across all chapters.'));for(const v of results.slice(0,50))content.append(button(v.key+' · '+v.text.slice(0,120),'nur-deen-search-hit',()=>loadReading(Number(v.key.split(':')[0]))));}
 if(active){content.append(el('h3','',active.chapter+'. '+active.name),note(active.editionName+' · '+active.count+' verses'));const start=page*20;for(const v of active.verses.slice(start,start+20))content.append(verseCard(v,active.translation));content.append(row(button('Previous','nur-power-small',()=>{page=Math.max(0,page-1);draw();}),el('span','nur-power-help',(page+1)+' / '+Math.ceil(active.count/20)),button('Next','nur-power-small',()=>{page=Math.min(Math.ceil(active.count/20)-1,page+1);draw();})));}
 else content.append(note('Choose a chapter to begin. Your bookmarks and reading progress are stored locally, separately from daily prayer completion.'));
 content.append(el('h3','','Bookmarked verses'));for(const key of r.bookmarks)content.append(button(key+' ↗','nur-power-small',()=>loadReading(Number(key.split(':')[0]))));
 content.append(el('h3','','Verified Dhikr'));drawDhikr();
}
function drawDhikr(){const date=today();for(const item of C.DHIKR){const count=dhikr[date]?.[item.id]||0,box=el('section','nur-deen-dhikr');box.append(el('h4','',item.title));if(item.arabic)box.append(el('p','nur-deen-arabic',item.arabic));if(item.meaning)box.append(el('p','nur-power-help',item.meaning));if(item.verse)box.append(button('Read Quran '+item.verse,'nur-power-small',()=>loadReading(Number(item.verse.split(':')[0]))));box.append(link(item.reference,item.url));if(item.note)box.append(note(item.note));const n=el('strong','nur-deen-count',String(count));box.append(row(button('−','nur-power-small',()=>countDhikr(item.id,-1)),n,button('+','nur-power-small',()=>countDhikr(item.id,1)),button('Reset today','nur-power-small',()=>countDhikr(item.id,-count))));content.append(box);}}
function countDhikr(id,delta){try{const next=clone(dhikr),date=today();next[date]={...(next[date]||{})};next[date][id]=Math.max(0,Math.min(100000,(next[date][id]||0)+delta));localStorage.setItem('nur-dhikr-v1',JSON.stringify(next));dhikr=next;draw();}catch{say('Unable to save the counter.');}}
/* Prayer companion: no location request, notification scheduling or completion occurs automatically. */
function zoneDate(zone,when=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(when);}
function calculate(){const p=data.prayer;if(!p.location){say('Select your location first.');return;}try{prayerTable=D.prayerTimes(window.adhan,p,zoneDate(p.location.timeZone));draw();}catch(e){fail(e);}}
function drawPrayer(){const p=data.prayer,l=p.location||{},form=el('form','nur-deen-form');form.append(note('Prayer times are calculated estimates, not confirmed local masjid times. Choose a method appropriate to your area and adjust them when necessary.'));
 const label=field('Location name',l.label||''),lat=field('Latitude',l.latitude??'','number'),lon=field('Longitude',l.longitude??'','number'),tz=field('IANA time zone',l.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone);lat.input.step=lon.input.step='any';
 const method=select('Calculation method',[['MuslimWorldLeague','Muslim World League'],['NorthAmerica','ISNA / North America'],['Egyptian','Egyptian'],['UmmAlQura','Umm al-Qura'],['Karachi','Karachi'],['Dubai','Dubai'],['Qatar','Qatar'],['Kuwait','Kuwait'],['Singapore','Singapore'],['Turkey','Turkey'],['MoonsightingCommittee','Moonsighting Committee']],p.method);
 const madhab=select('Asr calculation', [['shafi','Standard / Shafi'],['hanafi','Hanafi']],p.madhab);
 const high=select('High-latitude rule',[['middleofthenight','Middle of the night'],['seventhofthenight','Seventh of the night'],['twilightangle','Twilight angle']],p.highLatitude);
 form.append(label.wrap,row(lat.wrap,lon.wrap),tz.wrap,method.wrap,madhab.wrap,high.wrap);
 const offsets=el('div','nur-deen-offsets');offsets.append(el('h3','','Minute adjustments'));const offsetInputs={};for(const name of D.PRAYERS){const f=field(name[0].toUpperCase()+name.slice(1),p.offsets[name],'number');f.input.min='-120';f.input.max='120';f.input.step='1';offsetInputs[name]=f.input;offsets.append(f.wrap);}form.append(offsets);
 form.append(row(button('Use device location','nur-power-small',()=>{if(!navigator.geolocation){say('Device location is unavailable.');return;}say('Requesting location permission…');navigator.geolocation.getCurrentPosition(pos=>{lat.input.value=String(pos.coords.latitude);lon.input.value=String(pos.coords.longitude);say('Location filled. Review the time zone and save.');},()=>say('Location permission denied or unavailable. Enter coordinates manually.'),{enableHighAccuracy:false,timeout:15000,maximumAge:60000});}),button('Save and calculate','nur-power-primary',()=>{try{const latitude=Number(lat.input.value),longitude=Number(lon.input.value);if(!lat.input.value||!lon.input.value||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)throw Error('Enter valid coordinates.');new Intl.DateTimeFormat('en',{timeZone:tz.input.value});const offsets={};for(const n of D.PRAYERS){const v=Number(offsetInputs[n].value);if(!Number.isInteger(v)||v<-120||v>120)throw Error('Offsets must be whole minutes from −120 to 120.');offsets[n]=v;}if(change(s=>{s.prayer.location={latitude,longitude,timeZone:tz.input.value,label:label.input.value||'Selected location'};s.prayer.method=method.input.value;s.prayer.madhab=madhab.input.value;s.prayer.highLatitude=high.input.value;s.prayer.offsets=offsets;})){prayerTable=null;calculate();}}catch(e){fail(e);}})));
 content.append(form);
 if(prayerTable){content.append(el('h3','','Today · '+prayerTable.date),note(prayerTable.location.label+' · '+prayerTable.method+' · '+prayerTable.timeZone));const grid=el('div','nur-deen-timetable');for(const name of D.PRAYERS){const f=field(name[0].toUpperCase()+name.slice(1),D.formatPrayer(prayerTable,name),'time');const saveButton=button('Save correction','nur-power-small',()=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(f.input.value)){say('Enter a valid local time.');return;}if(change(s=>{s.prayer.manual[prayerTable.date]={...(s.prayer.manual[prayerTable.date]||{}),[name]:f.input.value};})){prayerTable.manual={...prayerTable.manual,[name]:f.input.value};draw();}});grid.append(row(f.wrap,saveButton));}content.append(grid);content.append(note('Manual corrections are saved for this date. They do not change your prayer checkboxes or historical completion.'));
 content.append(button('Clear today’s corrections','nur-power-small',()=>{if(change(s=>{delete s.prayer.manual[prayerTable.date];})){prayerTable.manual={};draw();}}));
 const next=el('p','nur-deen-next');next.id='nurDeenNext';content.append(next);updateCountdown();
 content.append(checkbox('Enable prayer-time reminders',p.reminders,checked=>{if(checked)enableReminders();else disableReminders();}));content.append(note('Notifications require the supported Android plugin and permission. Android may delay or restrict delivery; exact timing is not guaranteed. No prayer is marked complete automatically.'));
 content.append(button('Open prayer checklist ↗','nur-power-small',()=>{close();window.openModal?.('prayers');}));}
}
async function notificationPlugin(){const cap=window.Capacitor;if(!cap?.isNativePlatform?.()||!cap.registerPlugin||cap.isPluginAvailable&&!cap.isPluginAvailable('LocalNotifications'))throw Error('Native reminders are unavailable in this build.');return cap.registerPlugin('LocalNotifications');}
async function cancelReminders(plugin){await plugin.cancel({notifications:Array.from({length:10},(_,i)=>({id:515000+i}))});}
async function enableReminders(){await run(async()=>{const plugin=await notificationPlugin();let permission=await plugin.checkPermissions();if(permission.display!=='granted')permission=await plugin.requestPermissions();if(permission.display!=='granted')throw Error('Notification permission was not granted.');if(!prayerTable)throw Error('Calculate prayer times first.');const times=[];const base=new Date();for(let day=0;day<2;day++){const d=new Date(base);d.setDate(d.getDate()+day);times.push(D.prayerTimes(window.adhan,data.prayer,zoneDate(data.prayer.location.timeZone,d)));}const notifications=[];for(let i=0;i<times.length;i++)for(let j=0;j<5;j++){const t=times[i],name=D.PRAYERS[j];const at=new Date(t.instants[name]);if(at.getTime()>Date.now())notifications.push({id:515000+i*5+j,title:'NUR · '+name[0].toUpperCase()+name.slice(1),body:'Prayer time reminder. Check your local masjid timetable.',schedule:{at},extra:{nur:'prayer',name,date:t.date}});}await cancelReminders(plugin);await plugin.schedule({notifications});if(!change(s=>{s.prayer.reminders=true;}))await cancelReminders(plugin);else say('Reminders scheduled with Android. Delivery depends on device permissions and restrictions.');});}
async function disableReminders(){await run(async()=>{try{const plugin=await notificationPlugin();await cancelReminders(plugin);}catch(e){if(data.prayer.reminders)throw e;}change(s=>{s.prayer.reminders=false;});say('NUR prayer reminders disabled.');});}
function updateCountdown(){const node=doc.querySelector('#nurDeenNext');if(!node||!prayerTable)return;try{const p=data.prayer;const tables=[prayerTable];const tomorrow=new Date(prayerTable.date+'T12:00:00Z');tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tables.push(D.prayerTimes(window.adhan,p,tomorrow.toISOString().slice(0,10)));const next=D.nextPrayer(tables,Date.now());if(!next){node.textContent='No upcoming time available.';return;}const minutes=Math.max(0,Math.ceil((Date.parse(next.instant)-Date.now())/60000));node.textContent='Next: '+next.name+' · '+Math.floor(minutes/60)+'h '+String(minutes%60).padStart(2,'0')+'m';}catch{node.textContent='Countdown unavailable.';}}
/* Gemini: keys are session-only by default; encrypted saving requires a user passphrase. */
function drawAI(){const a=data.ai;content.append(note('NUR AI is optional. Enter your own Gemini API key. Direct client-side keys are not fully protected against a compromised device. Only the text you send and any explicitly selected context are transmitted to Google.'));
 const keySection=el('section','nur-deen-key-section');keySection.append(el('h3','','API key settings'));
 const keyField=field('Gemini API key','','password');keyField.input.autocomplete='off';keyField.input.spellcheck=false;const pass=field('Passphrase for encrypted storage','','password');pass.input.autocomplete='new-password';
 keySection.append(keyField.wrap,row(button('Show / hide','nur-power-small',()=>{keyField.input.type=keyField.input.type==='password'?'text':'password';}),button('Use for this session','nur-power-small',()=>{try{store.setSession(keyField.input.value);keyField.input.value='';say('API key active in memory for this session.');draw();}catch(e){fail(e);}})),pass.wrap);
 keySection.append(row(button('Save encrypted','nur-power-small',()=>run(async()=>{await store.save(keyField.input.value,pass.input.value);keyField.input.value='';pass.input.value='';say('Key encrypted and saved on this device. Keep your passphrase safe.');})),button('Unlock saved key','nur-power-small',()=>run(async()=>{await store.unlock(pass.input.value);pass.input.value='';say('Saved key unlocked.');})),button('Lock session','nur-power-small',()=>{store.lock();say('Key cleared from active memory.');draw();}),button('Delete saved key','nur-power-danger',()=>{if(window.confirm('Delete the saved API key and clear the active key?'))run(async()=>{await store.clear();say('Saved and active API key deleted.');});})));
 keySection.append(note('Encrypted saving uses AES-256-GCM and a passphrase-derived key. The passphrase is never saved. A forgotten passphrase cannot be recovered. Session-only mode stores no key on disk.'));
 keySection.append(link('Create or manage a Gemini API key ↗','https://aistudio.google.com/app/apikey'));content.append(keySection);
 const model=select('Gemini model',modelOptions.map(x=>[x.name,x.label]),a.model);model.input.addEventListener('change',()=>change(s=>{s.ai.model=model.input.value;}));content.append(row(model.wrap,button('Find available models','nur-power-small',()=>run(async()=>{modelOptions=await store.use(key=>D.models(fetch,key));if(!modelOptions.length)throw Error('No supported text models were returned.');if(!modelOptions.some(x=>x.name===data.ai.model))change(s=>{s.ai.model=modelOptions[0].name;});say(modelOptions.length+' compatible models found.');})),button('Test connection','nur-power-small',()=>run(async()=>{if(!data.ai.model)throw Error('Choose a model first.');const result=await store.use(key=>D.generate(fetch,key,data.ai.model,D.requestBody([],'Reply with the single word OK.'),undefined));say('Gemini responded successfully. '+result.slice(0,80));}))));
 const manual=field('Model ID (optional)',a.model.replace(/^models\//,''));manual.input.placeholder='Choose from available models';content.append(row(manual.wrap,button('Use model ID','nur-power-small',()=>{try{change(s=>{s.ai.model=D.modelName(manual.input.value);});}catch(e){fail(e);}})));
 const privacy=checkbox('Keep chat history on this device',a.saveHistory,checked=>{change(s=>{s.ai.saveHistory=checked;if(!checked)s.ai.history=[];});});content.append(privacy);
 const chat=el('div','nur-deen-chat');for(const msg of a.history){const bubble=el('div','nur-deen-message '+msg.role);bubble.append(el('small','',msg.role==='user'?'You':'NUR AI'),el('p','',msg.text));chat.append(bubble);}content.append(chat);
 const input=el('textarea','nur-power-input nur-deen-chat-input');input.rows=3;input.maxLength=12000;input.placeholder='Ask an Islamic learning question…';content.append(input);
 let contextCheck=null;if(selectedReference){contextCheck=checkbox('Include Quran '+selectedReference+' as verified reference context',false,()=>{});content.append(contextCheck);content.append(button('Clear selected reference','nur-power-small',()=>{selectedReference=null;draw();}));}
 const send=button('Send to NUR AI','nur-power-primary',()=>{const question=input.value.trim(),include=!!contextCheck?.querySelector('input').checked;if(!question)return;run(async()=>{if(!data.ai.model)throw Error('Choose a Gemini model first.');controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),45000);try{let context='';if(include&&selectedReference){const ref=await loadVerse(selectedReference);context='Quran '+ref.key+'\nArabic: '+ref.arabic+'\n'+ref.source+': '+ref.translation;}const history=data.ai.history;const body=D.requestBody(history,question,context);const answer=await store.use(key=>D.generate(fetch,key,data.ai.model,body,controller.signal));if(data.ai.saveHistory)change(s=>{s.ai.history=[...s.ai.history,{role:'user',text:question},{role:'model',text:answer}].slice(-40);});else{sessionMessages.push({role:'user',text:question},{role:'model',text:answer});}say('Response received. Verify religious references before relying on them.');}finally{clearTimeout(timeout);controller=null;}});});
 const cancel=button('Cancel request','nur-power-small',()=>controller?.abort());cancel.disabled=!busy;content.append(row(send,cancel,button('Clear conversation','nur-power-danger',()=>{if(window.confirm('Clear the NUR AI conversation?')){sessionMessages.length=0;change(s=>{s.ai.history=[];});draw();}})));
 content.append(note('AI explanations are not fatwas. The assistant must distinguish verified sources from generated commentary. No personal tracking data is sent unless you explicitly select it.'));
}
const sessionMessages=[];
window.NURDeenUI={open,close,getState:()=>clone(data),setState:save,loadReading,calculate,lockKey:()=>store.lock(),hasKey:()=>store.hasKey()};
window.setInterval(()=>{if(!doc.hidden&&dialog.open&&tab==='prayer')updateCountdown();},30000);
window.addEventListener('pagehide',()=>store.lock());
})();